### ISSUE TITLE
Pagination for transactions view

### ISSUE THREAD

**Issue by iokiwi** [iokiwi/moneyapp#13]
Currently the transactions index view pulls back all transactions at once. We should paginate this view.

**Comment by tehnools** [comment]
Would you like this pagination to be a fixed number of entries or dynamic? 25 entries sounds ok?

**Comment by tehnools** [comment]
@iokiwi  watchu think?
<img width="1486" alt="image" src="https://github.com/iokiwi/moneyapp/assets/20850573/1212b913-c765-47e5-8568-9f04d73e5ca2">
<img width="1486" alt="image" src="https://github.com/iokiwi/moneyapp/assets/20850573/dbbab188-59a9-4952-8b1a-504e4b9a2b22">

**Comment by tehnools** [comment]
did something like this @iokiwi 
Simple
<img width="382" alt="image" src="https://github.com/iokiwi/moneyapp/assets/20850573/6ec69d26-8514-44c6-9682-b64d0f9c9d0e">
