### ISSUE TITLE
Feature include inbound vs outbound transactions

### ISSUE THREAD

**Issue by noelsoong** [iokiwi/moneyapp#4]
Currently the information for average and total is not sufficient. Would be nice to include average incoming and outgoing expenses. 

Current view of transactions page.
<img width="687" alt="image" src="https://github.com/iokiwi/moneyapp/assets/127056857/7c20322b-6fc0-45d0-9a61-81f2b1fd05a7">

## Proposed view
TOTAL
_______
AVERAGE
_______
COUNT
_______
INBOUND
________
OUTBOUD
_________
NET INCOME

**Comment by iokiwi** [comment]
NB the financial nomenclature for Inbound/Outbound is Credit/Debit respectively.

I suggest separate summaries for account Credits and account Debits.

.e.g.

||Credit|Debit|Total|
|---|---|---|---|
|Net||||
|Average||||
|Count||||

**Comment by tehnools** [comment]
pr here
https://github.com/iokiwi/moneyapp/pull/7
